Website/Controllers/CheckoutController.cs
// --------------------------------------------------------------------------------------------------------------------
// <copyright file="CheckoutController.cs" company="Sitecore Corporation">
//   Copyright (c) Sitecore Corporation 1999-2016
// </copyright>
// <summary>
//   Defines the checkout controller type.
// </summary>
// --------------------------------------------------------------------------------------------------------------------
// Copyright 2016 Sitecore Corporation A/S
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file 
// except in compliance with the License. You may obtain a copy of the License at
//       http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the 
// License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, 
// either express or implied. See the License for the specific language governing permissions 
// and limitations under the License.
// ---------------------------------------------------------------------
namespace Sitecore.Commerce.StarterKit.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web.Mvc;
    using Entities.Payments;
    using Filters;
    using Helpers;
    using Sitecore.Commerce.Entities;
    using Sitecore.Commerce.Entities.Carts;
    using Sitecore.Commerce.Entities.Shipping;
    using Sitecore.Commerce.StarterKit.Models;
    using Sitecore.Commerce.StarterKit.Services;
    using Sitecore.Diagnostics;
    using System.Globalization;
    using Sitecore.Commerce.PaymentService.Connector;

    /// <summary>
    /// The checkout controller.
    /// </summary>
    public class CheckoutController : Controller
    {
        /// <summary>
        /// The checkout service.
        /// </summary>
        private readonly ICheckoutService checkoutService;

        /// <summary>
        /// The cart service.
        /// </summary>
        private readonly ICartService cartService;

        /// <summary>
        /// The cart service.
        /// </summary>
        private readonly IOrderService orderService;

        /// <summary>
        /// Initializes a new instance of the <see cref="CheckoutController"/> class.
        /// </summary>
        /// <param name="checkoutService">The checkout service.</param>
        /// <param name="cartService">The cart service.</param>
        /// <param name="orderService">The orders service.</param>
        public CheckoutController([NotNull] ICheckoutService checkoutService, [NotNull] ICartService cartService, [NotNull] IOrderService orderService)
        {
            Assert.ArgumentNotNull(checkoutService, "checkoutService");
            Assert.ArgumentNotNull(cartService, "cartService");
            Assert.ArgumentNotNull(orderService, "orderService");

            this.checkoutService = checkoutService;
            this.cartService = cartService;
            this.orderService = orderService;
        }

        /// <summary>
        /// Views the index.
        /// </summary>
        /// <returns>The action result.</returns>
        [RequireCartLine]
        public ActionResult Index()
        {
            ViewBag.Countries = Context.Database.Items["/sitecore/system/Settings/Analytics/Lookups/Countries/"];
            return View("Index");
        }

        /// <summary>
        /// Views the billing address.
        /// </summary>
        /// <returns>The action result.</returns>
        [HttpGet]
        public ActionResult BillingAddress()
        {
            ViewBag.Countries = Context.Database.Items["/sitecore/system/Settings/Analytics/Lookups/Countries/"];

            var address = this.cartService.GetBillingAddress();
            if (address == null)
            {
                address = this.cartService.GetAddresses().FirstOrDefault() ?? new Party();
            }

            ViewBag.Addresses = this.cartService.GetAddresses().Select(a => a.ToAddressModel());

            var billingAddress = address.ToAddressModel();

            return View("BillingAddress", billingAddress);
        }

        /// <summary>
        /// Views the billing address.
        /// </summary>
        /// <param name="billingAddress">The user address.</param>
        /// <param name="changeStep">The change step type.</param>
        /// <returns>The action result.</returns>
        [HttpPost]
        public ActionResult BillingAddress(AddressModel billingAddress, ChangeStepType changeStep)
        {
            ViewBag.Countries = Context.Database.Items["/sitecore/system/Settings/Analytics/Lookups/Countries/"];
            ViewBag.Addresses = this.cartService.GetAddresses().Select(a => a.ToAddressModel());

            if (changeStep != ChangeStepType.Next || !this.ModelState.IsValid)
            {
                return View(billingAddress);
            }

            // If address is not new
            if (!string.IsNullOrEmpty(billingAddress.PartyId))
            {
                if (billingAddress.IsChanged((AddressModel)TempData["billing_address"]))
                {
                    this.cartService.UpdateAddresses(new List<Party>() { billingAddress.ToParty() });
                }

                this.cartService.SetBillingAddressToCart(new CartParty()
                {
                    ExternalId = billingAddress.PartyId,
                    PartyID = billingAddress.PartyId
                });

                // proceed to next step
                return this.RedirectToAction("ShippingAddress");
            }

            // Add a new address to customer
            var party = billingAddress.ToParty();
            var addresses = this.cartService.AddAddress(party);

            var address = addresses.FirstOrDefault(a => a.FirstName == party.FirstName && a.LastName == party.LastName && a.Email == party.Email);

            if (address == null)
            {
                this.ModelState.AddModelError(string.Empty, "Address could not be added to cart");
                return View(billingAddress);
            }

            var result = this.cartService.SetBillingAddressToCart(new CartParty
            {
                ExternalId = address.ExternalId,
                PartyID = address.PartyId
            });

            if (!result)
            {
                this.ModelState.AddModelError(string.Empty, "Could not update billing address");
                return View(billingAddress);
            }

            // proceed to next step
            return this.RedirectToAction("ShippingAddress");
        }

        /// <summary>
        /// Gets a billing address.
        /// </summary>
        /// <param name="id">The address party ID.</param>
        /// <returns>The Json content.</returns>
        [HttpGet]
        public JsonResult GetBillingAddress(string id)
        {
            var addressMmodel = this.cartService.GetAddresses().Select(a => a.ToAddressModel());
            return Json(addressMmodel.FirstOrDefault(m => m.PartyId == id), JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// Views the Shipping address.
        /// </summary>
        /// <returns>The action result.</returns>
        [HttpGet]
        public ActionResult ShippingAddress()
        {
            ViewBag.Countries = Context.Database.Items["/sitecore/system/Settings/Analytics/Lookups/Countries/"];
            var address = this.cartService.GetShippingAddress() ?? this.cartService.GetBillingAddress();
            if (address == null)
            {
                address = this.cartService.GetAddresses().FirstOrDefault() ?? new Party();
            }

            ViewBag.Addresses = this.cartService.GetAddresses().Select(a => a.ToAddressModel());

            var shippingAddress = address.ToAddressModel();
            TempData["shipping_address"] = shippingAddress;

            return View("ShippingAddress", shippingAddress);
        }

        /// <summary>
        /// Views the shipping address.
        /// </summary>
        /// <param name="shippingAddress">The address model.</param>
        /// <param name="changeStep">The change step type.</param>
        /// <returns>The action result.</returns>
        [HttpPost]
        public ActionResult ShippingAddress(AddressModel shippingAddress, ChangeStepType changeStep)
        {
            ViewBag.Countries = Context.Database.Items["/sitecore/system/Settings/Analytics/Lookups/Countries/"];
            ViewBag.Addresses = this.cartService.GetAddresses().Select(a => a.ToAddressModel());

            if (changeStep == ChangeStepType.Previous)
            {
                this.ModelState.Clear();

                return this.RedirectToAction("BillingAddress");
            }

            if (!this.ModelState.IsValid)
            {
                return View(shippingAddress);
            }

            // If address is not new
            if (!string.IsNullOrEmpty(shippingAddress.PartyId))
            {
                if (shippingAddress.IsChanged((AddressModel)TempData["shipping_address"]))
                {
                    this.cartService.UpdateAddresses(new List<Party>() { shippingAddress.ToParty() });
                }

                this.cartService.SetShippingAddressToCart(new CartParty()
                {
                    ExternalId = shippingAddress.PartyId,
                    PartyID = shippingAddress.PartyId
                });

                // proceed to next step
                return this.RedirectToAction("ShippingMethod");
            }

            var party = shippingAddress.ToParty();
            var addresses = this.cartService.AddAddress(party);

            var address = addresses.FirstOrDefault(a => a.FirstName == party.FirstName && a.LastName == party.LastName && a.Email == party.Email);

            if (address == null)
            {

Website/Views/Checkout/BillingAddress.cshtml
@*//-----------------------------------------------------------------------
    // Copyright 2016 Sitecore Corporation A/S
    // Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file
    // except in compliance with the License. You may obtain a copy of the License at
    //       http://www.apache.org/licenses/LICENSE-2.0
    //
    // Unless required by applicable law or agreed to in writing, software distributed under the
    // License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
    // either express or implied. See the License for the specific language governing permissions
    // and limitations under the License.
    // -------------------------------------------------------------------------------------------*@
@using Sitecore.Commerce.StarterKit.Models
@using Sitecore.Commerce.StarterKit.Helpers
@model AddressModel

@Html.Hidden("stepNumber", 1)
@Html.Hidden("stepAction", Url.Action("BillingAddress"))

<h4>Step 1 : Billing Details</h4>
<hr />

<div class="row">
    <div class="col-md-6">
        <label>Select a billing address from your address book or enter a new address.</label>
        <select class="form-control billing-address-control">
            @foreach (var address in ViewBag.Addresses)
            {
                <option value="@address.PartyId" @(address.PartyId == Model.PartyId ? "selected" : "")>@(((AddressModel) address).DisplayName())</option>
            }
            <option value="new_address">New Address</option>
        </select>
    </div>
</div>

<br/>

<div class="form-address">
<div class="row">
  <div>
    @Html.ValidationSummary(true, null, new { @class = "text-danger" })
    @Html.HiddenFor(m => m.PartyId, new { @class = "form-control" })
  </div>
</div>
<div class="row">
  <div class="col-md-2">
    @Html.LabelFor(m => m.FirstName, new { @class = "control-label" })
  </div>
  <div class="col-md-4">
    @Html.TextBoxFor(m => m.FirstName, new { @class = "form-control" })
  </div>
  <div class="col-md-4 text-danger">
    @Html.ValidationMessageFor(m => m.FirstName)
  </div>
</div>

<div class="row">
  <div class="col-md-2">
    @Html.LabelFor(m => m.LastName, new { @class = "control-label" })
  </div>
  <div class="col-md-4">
    @Html.TextBoxFor(m => m.LastName, new { @class = "form-control" })
  </div>
  <div class="col-md-4 text-danger">
    @Html.ValidationMessageFor(m => m.LastName)
  </div>
</div>

<div class="row">
  <div class="col-md-2">
    @Html.LabelFor(m => m.Email, new { @class = "control-label" })
  </div>
  <div class="col-md-4">
    @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
  </div>
  <div class="col-md-4 text-danger">
    @Html.ValidationMessageFor(m => m.Email)
  </div>
</div>

<div class="row">
  @Html.LabelFor(m => m.Company, new { @class = "col-md-2 control-label" })
  <div class="col-md-4">
    @Html.TextBoxFor(m => m.Company, new { @class = "form-control" })
  </div>
  <div class="col-md-4 text-danger">
    @Html.ValidationMessageFor(m => m.Company)
  </div>
</div>

<div class="row">
  @Html.LabelFor(m => m.Country, new { @class = "col-md-2 control-label" })
      <div class="col-md-4">
        <select name="Country" class="form-control">
          <option value="">Please select the country</option>
          @foreach (Sitecore.Data.Items.Item child in ViewBag.Countries.Children)
          {
            <option value="@child.Fields["Country code"]" @(Model.Country == child.Fields["Country code"].ToString() ? "selected" : "")>@child.Name</option>
          }
        </select>
      </div>
  <div class="col-md-4 text-danger">
    @Html.ValidationMessageFor(m => m.Country)
  </div>
</div>

<div class="row">
  @Html.LabelFor(m => m.State, new { @class = "col-md-2 control-label" })
  <div class="col-md-4">
    @Html.TextBoxFor(m => m.State, new { @class = "form-control" })
  </div>
  <div class="col-md-4 text-danger">
    @Html.ValidationMessageFor(m => m.State)
  </div>
</div>

<div class="row">
  @Html.LabelFor(m => m.City, new { @class = "col-md-2 control-label" })
  <div class="col-md-4">
    @Html.TextBoxFor(m => m.City, new { @class = "form-control" })
  </div>
  <div class="col-md-4 text-danger">
    @Html.ValidationMessageFor(m => m.City)
  </div>
</div>

<div class="row">
  @Html.LabelFor(m => m.Address1, new { @class = "col-md-2 control-label" })
  <div class="col-md-4">
    @Html.TextBoxFor(m => m.Address1, new { @class = "form-control" })
  </div>
  <div class="col-md-4 text-danger">
    @Html.ValidationMessageFor(m => m.Address1)
  </div>
</div>

<div class="row">
  @Html.LabelFor(m => m.Address2, new { @class = "col-md-2 control-label" })
  <div class="col-md-4">
    @Html.TextBoxFor(m => m.Address2, new { @class = "form-control" })
  </div>
  <div class="col-md-4 text-danger">
  </div>
</div>

<div class="row">
  @Html.LabelFor(m => m.ZipPostalCode, new { @class = "col-md-2 control-label" })
  <div class="col-md-4">
    @Html.TextBoxFor(m => m.ZipPostalCode, new { @class = "form-control" })
  </div>
  <div class="col-md-4 text-danger">
    @Html.ValidationMessageFor(m => m.ZipPostalCode)
  </div>
</div>

<div class="row">
  @Html.LabelFor(m => m.PhoneNumber, new { @class = "col-md-2 control-label" })
  <div class="col-md-4">
    @Html.TextBoxFor(m => m.PhoneNumber, new { @class = "form-control" })
  </div>
  <div class="col-md-4 text-danger">
    @Html.ValidationMessageFor(m => m.PhoneNumber)
  </div>
</div>
</div>
<hr />

<div class="row">
    <div class="col-md-offset-4 col-md-4">
        <button type="submit" name="changeStep" value="@ChangeStepType.Next" class="btn btn-success" data-loading-text="Loading...">Next</button>
    </div>
</div>

Website/Views/Checkout/CheckoutArrows.cshtml
@*//-----------------------------------------------------------------------
    // Copyright 2016 Sitecore Corporation A/S
    // Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file
    // except in compliance with the License. You may obtain a copy of the License at
    //       http://www.apache.org/licenses/LICENSE-2.0
    //
    // Unless required by applicable law or agreed to in writing, software distributed under the
    // License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
    // either express or implied. See the License for the specific language governing permissions
    // and limitations under the License.
    // -------------------------------------------------------------------------------------------*@
<div id="checkoutArrows">
  <div class="row">
    <div class="col-md-2">
      <div class="arrow_box selected">
        <h2 class="logo">Billing address</h2>
      </div>
    </div>
    <div class="col-md-2">
      <div class="arrow_box">
        <h2 class="logo">Shipping address</h2>
      </div>
    </div>
    <div class="col-md-2">
      <div class="arrow_box">
        <h2 class="logo">Shipping Method</h2>
      </div>
    </div>
    <div class="col-md-2">
      <div class="arrow_box">
        <h2 class="logo">Payment Method</h2>
      </div>
    </div>
    <div class="col-md-2">
      <div class="arrow_box">
        <h2 class="logo">Payment Info</h2>
      </div>
    </div>
    <div class="col-md-2">
      <div class="arrow_box">
        <h2 class="logo">Confirm Order</h2>
      </div>
    </div>
  </div>
</div>

Website/Views/Checkout/Confirmation.cshtml
@*//-----------------------------------------------------------------------
    // Copyright 2016 Sitecore Corporation A/S
    // Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file
    // except in compliance with the License. You may obtain a copy of the License at
    //       http://www.apache.org/licenses/LICENSE-2.0
    //
    // Unless required by applicable law or agreed to in writing, software distributed under the
    // License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
    // either express or implied. See the License for the specific language governing permissions
    // and limitations under the License.
    // -------------------------------------------------------------------------------------------*@
@using Sitecore.Commerce.StarterKit.Models
@using System.Web.Optimization
@model ConfirmModel
@Html.Hidden("stepNumber", 6)
@Html.Hidden("stepAction", Url.Action("Confirmation"))

<h4>Step 6 : Confirmation</h4>
<hr/>
<div class="row">
    <div class="col-md-3">
        <h5><strong>Billing Address</strong></h5>
        <div>@(Model.BillingAddress.FirstName + " " + Model.BillingAddress.LastName)</div>
        <div>Email: @Model.BillingAddress.Email</div>
        <div>Company: @Model.BillingAddress.Company</div>
        <div>Country: @Model.BillingAddress.Country</div>
        <div>City: @Model.BillingAddress.City</div>
        <div>Address1: @Model.BillingAddress.Address1</div>
        <div>Address2: @Model.BillingAddress.Address2</div>
        <div>Zip: @Model.BillingAddress.ZipPostalCode</div>
        <div>Phone: @Model.BillingAddress.PhoneNumber</div>
    </div>

    <div class="col-md-3">
        <h5><strong>Shipping Address</strong></h5>
        <div>@(Model.ShippingAddress.FirstName + " " + Model.ShippingAddress.LastName)</div>
        <div>Email: @Model.ShippingAddress.Email</div>
        <div>Company: @Model.ShippingAddress.Company</div>
        <div>Country: @Model.ShippingAddress.Country</div>
        <div>City: @Model.ShippingAddress.City</div>
        <div>Address1: @Model.ShippingAddress.Address1</div>
        <div>Address2: @Model.ShippingAddress.Address2</div>
        <div>Zip: @Model.ShippingAddress.ZipPostalCode</div>
        <div>Phone: @Model.ShippingAddress.PhoneNumber</div>
    </div>

    <div class="col-md-3">
        <h5><strong>Payment Method</strong></h5>
        <div>@Model.PaymentMethod</div>
    </div>

    <div class="col-md-3">
        <h5><strong>Shipping Method</strong></h5>
        <div>@Model.ShippingMethod</div>
    </div>
</div>

@Html.Partial("Products")

<hr />

<div class="row">
    <div class="col-md-4">
        <button type="submit" name="changeStep" value="@ChangeStepType.Previous" class="btn btn-default" data-loading-text="Loading...">Previous</button>
    </div>
    <div class="col-md-4">
        <button type="submit" name="changeStep" value="@ChangeStepType.Confirm" class="btn btn-success" data-loading-text="Loading...">Confirm</button>
    </div>
</div>

Website/Views/Checkout/Index.cshtml
@*//-----------------------------------------------------------------------
    // Copyright 2016 Sitecore Corporation A/S
    // Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file
    // except in compliance with the License. You may obtain a copy of the License at
    //       http://www.apache.org/licenses/LICENSE-2.0
    //
    // Unless required by applicable law or agreed to in writing, software distributed under the
    // License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
    // either express or implied. See the License for the specific language governing permissions
    // and limitations under the License.
    // -------------------------------------------------------------------------------------------*@
@using System.Web.Optimization

@Html.Partial("CheckoutArrows")

<div id="checkoutContainer" class="form-group">
  @{
    const string FormId = "checkoutForm";

    var options = new AjaxOptions
    {
      UpdateTargetId = FormId,
      OnSuccess = "updateWizard"
    };
  }

  @using (Ajax.BeginForm("BillingAddress", "Checkout", options, new { id = FormId }))
  {
    @Html.Action("BillingAddress")
  }
</div>

@Scripts.Render("~/bundles/Commerce/paymentservice")

<script type="text/javascript">
    
    function updateWizard(context) {
        var stepNumber = $(this).find('#stepNumber').val();
        var stepAction = $(this).find('#stepAction').val();

        $('#checkoutForm').attr("action", stepAction);

        var arrows = $('#checkoutArrows div.arrow_box');

        arrows.removeClass("selected");

        arrows.slice(0, stepNumber).addClass("selected");

        if (stepNumber == 6) {
            var cinfirmApi = new ConfirmApi();
            cinfirmApi.showProducts();
        }
    }

    registerEventListener();

</script>

Website/Views/Checkout/PaymentMethod.cshtml
@*//-----------------------------------------------------------------------
    // Copyright 2016 Sitecore Corporation A/S
    // Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file
    // except in compliance with the License. You may obtain a copy of the License at
    //       http://www.apache.org/licenses/LICENSE-2.0
    //
    // Unless required by applicable law or agreed to in writing, software distributed under the
    // License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
    // either express or implied. See the License for the specific language governing permissions
    // and limitations under the License.
    // -------------------------------------------------------------------------------------------*@
@using Sitecore.Commerce.StarterKit.Models
@model IEnumerable<PaymentOptionModel>
@Html.Hidden("stepNumber", 4)
@Html.Hidden("stepAction", Url.Action("PaymentMethod"))

@{
    var payInfo = Model.FirstOrDefault(m => m.Selected);
    int paymentTypeId = payInfo != null ? payInfo.OptionType : 0;
}

<h4>Step 4 : Payment Method</h4>
<hr />
<div class="row">
    <div class="col-md-3">
        <select class="form-control paymentoption-control">
            @foreach (var paymentInfo in Model)
            {
                <option value="@paymentInfo.OptionType" @(paymentInfo.Selected ? "selected" : "")>@paymentInfo.OptionName</option>
            }
        </select>
    </div>
</div>
<br/>
<div class="method-row">
    <div class="form-group" id="paymentMethods">
        @Html.Action("PaymentMethodList", new { id = paymentTypeId })
    </div>
</div>
<hr/>

<div class="row">
    <div class="col-md-4">
        <button type="submit" name="changeStep" value="@ChangeStepType.Previous" class="btn btn-default" data-loading-text="Loading...">Previous</button>
    </div>
    <div class="col-md-4">
        <button type="submit" name="changeStep" value="@ChangeStepType.Next" class="btn btn-success" data-loading-text="Loading...">Next</button>
    </div>
</div>

Website/Views/Checkout/PaymentMethodList.cshtml
@*//-----------------------------------------------------------------------
    // Copyright 2016 Sitecore Corporation A/S
    // Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file
    // except in compliance with the License. You may obtain a copy of the License at
    //       http://www.apache.org/licenses/LICENSE-2.0
    //
    // Unless required by applicable law or agreed to in writing, software distributed under the
    // License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
    // either express or implied. See the License for the specific language governing permissions
    // and limitations under the License.
    // -------------------------------------------------------------------------------------------*@
@using Sitecore.Commerce.StarterKit.Models
@model IEnumerable<PaymentMethodModel>


@foreach (var paymentMethod in Model)
{
    string radioId = Guid.NewGuid().ToString("N");
    <div class="row">
        <div class="col-md-3">
            <input type="radio" @(paymentMethod.Selected ? "checked=checked" : string.Empty) name="paymentMethod" id="@radioId" value="@(paymentMethod.SystemName + "|" + paymentMethod.Name)" />
            <label for="@radioId">@paymentMethod.Name</label>
        </div>
    </div>
}

Website/Views/Checkout/Products.cshtml
@*//-----------------------------------------------------------------------
    // Copyright 2016 Sitecore Corporation A/S
    // Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file
    // except in compliance with the License. You may obtain a copy of the License at
    //       http://www.apache.org/licenses/LICENSE-2.0
    //
    // Unless required by applicable law or agreed to in writing, software distributed under the
    // License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
    // either express or implied. See the License for the specific language governing permissions
    // and limitations under the License.
    // -------------------------------------------------------------------------------------------*@
@using System.Globalization
@using System.Web.Optimization
<div class="wrap-content-checkout" id="itemsContainer">
    <div class="col-md-12" id="cartSection" data-bind="visible: cartLines().length > 0" style="display: none;">
        <div class="table-responsive">
            <table class="table table-hover">
                <thead>
                    <tr class="cart-header">
                        <th class="hidden-sm hidden-xs">&nbsp;</th>
                        <th>Product details</th>
                        <th>Unit price</th>
                        <th>Quantity</th>
                        <th class="text-right">Total</th>
                    </tr>
                </thead>

                <tbody data-bind="foreach: cartLines">
                    <tr>
                        <td class="cart-image hidden-sm hidden-xs" pid="image">
                            <a data-bind="attr:{'href' : productUrl}"><img class="img-responsive" data-bind="attr: {src: image}" alt="a"  width ="100"/></a>
                        </td>

                        <td class="cart-info">
                            <a data-bind="attr:{'href' : productUrl}"><h5 pid="displayName" data-bind="text: productName"></h5></a>
                            <span class="cart-variable"></span>
                            <span pid="color"></span>
                        </td>

                        <td class="cart-price">
                            <dl>
                                <dt>
                                    <span pid="price" data-bind="text: unitPrice"></span>
                                </dt>
                            </dl>
                        </td>
                        <td class="cart-quantity text-center" style="width: 10%;">
                            <span data-bind="text: quantity"></span>
                        </td>
                        <td class="cart-total">
                            <dl>
                                <dt>
                                    <span pid="total" data-bind="text: totalLineSum"></span>
                                </dt>
                            </dl>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>

    <!-- curt summery-->
    <div data-bind="visible: cartLines().length > 0" id="summarySection" style="display: none;">
        <div class="col-md-12">
            @* MKL: We have two "Totals" so this will be removed until taxes and payment info added.
                <h3>Shopping Cart Total</h3>
            *@
        </div>
        <div class="col-md-12 total">
            <span class="text">TOTAL:</span>
            <span class="amount" data-bind="text: totalSum" />
        </div>
    </div>
</div>

Website/Views/Checkout/ShippingMethod.cshtml
@*//-----------------------------------------------------------------------
    // Copyright 2016 Sitecore Corporation A/S
    // Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file
    // except in compliance with the License. You may obtain a copy of the License at
    //       http://www.apache.org/licenses/LICENSE-2.0
    //
    // Unless required by applicable law or agreed to in writing, software distributed under the
    // License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
    // either express or implied. See the License for the specific language governing permissions
    // and limitations under the License.
    // -------------------------------------------------------------------------------------------*@
@using Sitecore.Commerce.StarterKit.Models
@model IEnumerable<ShippingInfoModel>
@Html.Hidden("stepNumber", 3)
@Html.Hidden("stepAction", Url.Action("ShippingMethod"))

@{
    var shippInfo = Model.FirstOrDefault(m => m.Selected);
    int optionTypeId = shippInfo != null ? shippInfo.OptionType : 0;
}

<h4>Step 3 : Shipping Method</h4>
<hr />
<div class="row">
  <div class="col-md-3">
    <select class="form-control shippingoption-control">
      @foreach (var shippingInfo in Model)
      {
        <option value="@shippingInfo.OptionType" @(shippingInfo.Selected ? "selected" : "")>@shippingInfo.OptionName</option>
      }
    </select>
  </div>
</div>
<br />
<div class="method-row">
    <div class="form-group" id="shippingMethods">
        @Html.Action("ShippingMethodList", new { id = optionTypeId })
    </div>
</div>
<hr />
<div class="row">
  <div class="col-md-4">
    <button type="submit" name="changeStep" value="@ChangeStepType.Previous" class="btn btn-default">Previous</button>
  </div>
  <div class="col-md-4">
    <button type="submit" name="changeStep" value="@ChangeStepType.Next" class="btn btn-success">Next</button>
  </div>
</div>